# Site
name: "Fit und Knusprig"
title: "Fit und Knusprig"
description: "Fit und Knusprig â€“ Frisch aus den Tiroler Alpen"
logo: 'assets/images/logo_large.png'
favicon: 'assets/images/logo_large.png'
baseurl: /fit-und-knusprig
#baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com

# Authors
authors:
  fynn:
    name: Fynn
    display_name: Fynn
    avatar: 'assets/images/fynn.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    #email: fynn@sharklasers.com
    #web: https://www.wowthemes.net/donate/
    #twitter: https://twitter.com/wowthemesnet
    description: "Student aus dem Norden"
  mavin:
    name: Mavin
    display_name: Mavin    
    avatar: 'assets/images/mavin.png'
    #gravatar: b1cc14991db7a456fcd761680bbc8f81
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "Sportstudent aus Innsbruck lelelel"
  emanuel:
    name: Emanuel
    display_name: Emanuel    
    avatar: 'assets/images/emanuel.jpg'
    #gravatar: b1cc14991db7a456fcd761680bbc8f81
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "Sportstudent aus Innsbruck lalalala"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
